language: java
jdk: oraclejdk8
language: java

 cache:
    directories:
     - $HOME/.cache
jobs:
  include:
    - stage: Clean
      script: ./mvnw clean
    - stage: Install
      script: ./mvnw install
    - stage: Package
      script: ./mvnw package
    - stage: Test
      script: ./mvnw test
