package com.yuma.app.document.enums;

public enum HealthLabels {
	VEGAN, VEGETARIAN, DAIRY_FREE, GLUTEN_FREE, WHEAT_FREE, EGG_FREE, MILK_FREE, PEANUT_FREE, TREE_NUT_FREE, SOY_FREE, FISH_FREE, SHELLFISH_FREE, PORK_FREE, RED_MEAT_FREE, ALCOHOL_FREE, NO_OIL_ADDED, NO_SUGAR_ADDED, KOSHER, HALAL
}
